log:
    stdout: true
    level: info

persistence:
    numHistoryShards: 4
    defaultStore: default
    visibilityStore: visibility
    datastores:
        default:
            cassandra:
                hosts: ""
                keyspace: "temporal"
                user: ""
                password: ""
                port: 9042
                maxConns: 20
                tls:
                    enabled: false
                    caFile: 
                    certFile: 
                    keyFile: 
                    caData: 
                    certData: 
                    keyData: 
                    enableHostVerification: false
                    serverName: 
        visibility:
            cassandra:
                hosts: ""
                keyspace: "temporal_visibility"
                user: ""
                password: ""
                port: 9042
                maxConns: 10
                tls:
                    enabled: false
                    caFile: 
                    certFile: 
                    keyFile: 
                    caData: 
                    certData: 
                    keyData: 
                    enableHostVerification: false
                    serverName: 

global:
    membership:
        maxJoinDuration: 30s
        broadcastAddress: "temporal"
    tls:
        internode:
            # This server section configures the TLS certificate that internal temporal
            # cluster nodes (history or matching) present to other clients within the Temporal Cluster. 
            server:
                requireClientAuth: false

                certFile: 
                keyFile: 
                clientCaFiles:
                    - 

                certData: 
                keyData: 
                clientCaData:
                    - 
            
            # This client section is used to configure the TLS clients within
            # the Temporal Cluster that connect to an Internode (history or matching)
            client:
                serverName: 
                disableHostVerification: false
                rootCaFiles:
                    - 
                rootCaData:
                    - 
        frontend:
            # This server section configures the TLS certificate that the Frontend
            # server presents to all clients (specifically the Worker role within
            # the Temporal Cluster and all External SDKs connecting to the Cluster)
            server:
                requireClientAuth: false
                certFile: 
                keyFile: 
                clientCaFiles:
                    - 
                    - 

                certData: 
                keyData: 
                clientCaData:
                    - 
                    - 
            
            # This client section is used to configure the TLS clients within
            # the Temporal Cluster (specifically the Worker role) that connect to the Frontend service
            client:
                serverName: 
                disableHostVerification: false
                rootCaFiles:
                    - 
                rootCaData:
                    - 
    authorization:
        jwtKeyProvider:
            keySourceURIs:
                - 
                - 
            refreshInterval: 1m
        permissionsClaimName: permissions
        authorizer: 
        claimMapper: 
services:
    frontend:
        rpc:
            grpcPort: 7233
            membershipPort: 6933
            bindOnIP: 172.24.0.4

    matching:
        rpc:
            grpcPort: 7235
            membershipPort: 6935
            bindOnIP: 172.24.0.4

    history:
        rpc:
            grpcPort: 7234
            membershipPort: 6934
            bindOnIP: 172.24.0.4

    worker:
        rpc:
            grpcPort: 7239
            membershipPort: 6939
            bindOnIP: 172.24.0.4

clusterMetadata:
    enableGlobalNamespace: false
    failoverVersionIncrement: 10
    masterClusterName: "active"
    currentClusterName: "active"
    clusterInformation:
        active:
            enabled: true
            initialFailoverVersion: 1
            rpcName: "frontend"
            rpcAddress: 127.0.0.1:7233

dcRedirectionPolicy:
    policy: "noop"
    toDC: ""

archival:
  history:
    state: "enabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"
  visibility:
    state: "enabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"

namespaceDefaults:
  archival:
    history:
      state: "disabled"
      URI: "file:///tmp/temporal_archival/development"
    visibility:
      state: "disabled"
      URI: "file:///tmp/temporal_vis_archival/development"

publicClient:
    hostPort: "172.24.0.4:7233"

dynamicConfigClient:
    filepath: "/etc/temporal/config/dynamicconfig"
    pollInterval: "60s"
